### ISSUE TITLE
Hyperpixel 4 not working with raspberry pi 5.

### ISSUE THREAD

**Issue by steveiliop56** [procount/pinn#819] opened 2024-06-03 09:08 UTC
**Describe the bug**
I am trying to use pinn with my hyperpixel display but nothing is displayed on it.

**To reproduce**
1. Connect a hyperpixel 4 to the raspberry pi 5 
2. Flash pinn from raspberry pi imager
3. Add the `dtoverlay=pimhyp4` to the config.txt in RECOVERY
4. Boot the pi

**Expected behaviour**
Pinn should have been displayed on the screen.

**Actual behaviour**
The screen shows nothing.

**System**
Add answers to the following questions:

* Which model of Raspberry Pi? Raspberry Pi 5
* Which version of PINN? Latest I guess its from raspberry pi imager.

**Comment by procount** [comment] 2024-06-03 09:13
Duplicate of #799.
Hyperpixels are not yet supported on Pi5 in PINN.

**Closed as completed by procount** 2024-06-03 09:13 UTC
