### ISSUE TITLE
[Feature] Add OpenBSD to OS List

### ISSUE THREAD

**Issue by jkhjhhbx** [procount/pinn#263] opened 2019-06-03 19:17 UTC
**Feature**: Support OpenBSD
**Why?**: OpenBSD is currently a bit of a pain to install on the Raspberry Pi. 
Hopefully, this could help push more users to the wonderful OS.

**Related Links**:
https://www.openbsd.org/arm64.html

https://ftp.openbsd.org/pub/OpenBSD/6.5/arm64/INSTALL.arm64

https://ftp.openbsd.org/pub/OpenBSD/snapshots/arm64/INSTALL.arm64

___________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75019602-feature-add-openbsd-to-os-list)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by procount** [comment] 2019-06-03 19:31
You're very welcome to have a go at converting it.
But you might want to have a read of the following issues first:
https://github.com/raspberrypi/noobs/issues/412
https://github.com/procount/pinn/issues/59

**Comment by lurch** [comment] 2019-06-04 11:59
@procount Perhaps this should be closed as a duplicate of #59 ?

**Comment by procount** [comment] 2019-06-04 12:30
Agreed

**Closed by procount** 2019-06-04 12:30 UTC

**Comment by jkhjhhbx** [comment] 2019-06-04 21:59
@procount @lurch #59 specifically states:

> FreeBSD (RPi3), RaspBSD, and NetBSD.

This issue is about OpenBSD, which is a whole other operating systems with its own complexities.

**Comment by lurch** [comment] 2019-06-04 23:07
@jkhjhhbx I had a read through some of the linked issues, and https://github.com/yzgyyang/freebsd-noobs/issues/1 is very informative - even the FreeBSD team themselves weren't able to get their OS working with NOOBS. So with no disrepect to @procount , I'd say the chance of him getting OpenBSD working in PINN is close to zero.

I suspect all the *BSDs will have similar boot/partitioning issues on NOOBS / PINN, so I think @procount should just add OpenBSD to the list in #59
